spring.application.name=SpringJPAPart2
spring.datasource.url=jdbc:mysql://localhost:3306/SpringJpaAssignment2
spring.datasource.username=Rohit
spring.datasource.password=RohitRawat-07
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

org.rohit.springjpapart2.repository.inheritance.singletable
org.rohit.springjpapart2.repository.inheritance.joined
org.rohit.springjpapart2.repository.inheritance.tableperclass



